### PR TITLE
fixed connectionUri for mongo checker

### PR DESCRIPTION
**Pull request by tkachuk**

### CODE REVIEW

**Comment by IgorTimoshenko** [comment]
+1

**Comment by lsmith77** [comment]
lets merge #83 first .. and then rebase this PR and hopefully it will be all green :)

**Comment by tkachuk** [comment]
What about this pull request?

**Comment by lsmith77** [comment]
can you rebase on master?

**Comment by weierophinney** [comment]
Thanks, @tkachuk! I rebased off of master, and added unit tests so we can verify the functionality going forward.

**Pull request merged**
